<?php

namespace ComitBlogBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
                    ->createQuery('select p from ComitBlogBundle:Product p ORDER BY  p.name ASC ')
                    ->getResult();
    }

}
